"""Writes docs/MASTERY_AUDIT.md from the Mastery trees (data/jjk/mastery): every kit's moves and the nodes on them.

    python3 tools/gen_mastery_doc.py
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), '..')
DATA = os.path.join(ROOT, 'src', 'main', 'resources', 'data', 'jjk', 'mastery')
TIER = {'SMALL': 'upgrade', 'MECHANICAL': '**mechanic**', 'MAJOR': '**milestone**', 'AWAKENING': '**AWAKENING**'}

index = json.load(open(os.path.join(DATA, 'index.json')))['trees']
out = ['# Mastery audit', '',
       'Generated by `tools/gen_mastery_doc.py` from `src/main/resources/data/jjk/mastery` (edit the trees, then re-run).',
       '', 'For each tree: its moves, every node on them (tier, cost, prerequisites) and what it changes. *Unlock* keys are the',
       'behaviours the code gates (`Mastery.unlocked`); *param* keys scale a move\'s numbers (`Mastery.param`).', '']
for f in index:
    t = json.load(open(os.path.join(DATA, f + '.json')))
    out += ['## ' + t['title'] + ' (`' + t['id'] + '`)', '']
    total = sum(n['cost'] for n in t['nodes'])
    out += ['%d nodes, %d Mastery to develop fully. Lanes: %s.' % (len(t['nodes']), total, ', '.join(t['lanes'])), '']
    out += ['| Move | Node | Tier | Cost | Needs | Effect |', '|---|---|---|---|---|---|']
    names = {n['id']: n['name'] for n in t['nodes']}
    for n in sorted(t['nodes'], key=lambda n: (n.get('move', ''), n['row'])):
        fx = []
        for e in n.get('effects', []):
            if 'unlock' in e:
                fx.append('unlock `%s`' % e['unlock'])
            elif 'mul' in e:
                fx.append('`%s` ×%g' % (e['param'], e['mul']))
            else:
                fx.append('`%s` +%g' % (e['param'], e['add']))
        out.append('| %s | %s | %s | %d | %s | %s |' % (n.get('move', '') or '—', n['name'], TIER[n['tier']], n['cost'],
                   ', '.join(names[r] for r in n.get('requires', [])) or '—', '; '.join(fx)))
    out.append('')
os.makedirs(os.path.join(ROOT, 'docs'), exist_ok=True)
open(os.path.join(ROOT, 'docs', 'MASTERY_AUDIT.md'), 'w').write('\n'.join(out) + '\n')
print('docs/MASTERY_AUDIT.md written')
